version: 2

multi-ecosystem-groups:
  appsec-stats-feed:
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "appsec-stats-feed"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "appsec-stats-feed"
